### ISSUE TITLE
Where condition, while confirmation user registration

### ISSUE THREAD

**Issue by ullakhan** [duffn/loopback-connector-arango#6]
Hi,
I am trying to integrate the ArangoDB with Loopback framework. It is working fine by following the steps mentioned in below article

https://strongloop.com/strongblog/getting-started-with-node-js-loopback-connector-for-arangodb/

I am using the below code for user registration just to confirm the successful registration.
https://github.com/strongloop/loopback-faq-user-management.git

But I m having a problem while confirming a user registration process after send Email to a user.
In Browser:

http://0.0.0.0:3000/api/MUsers/confirm?uid=150373302744&redirect=/verified&token=802d5753050dec690048bd474266de72bc7bd841f1ee786dd5f5a36202a6a33850a98968b826dc08e9bde1fd93b86f1df918f7c2f2921bc847c5962f6ea488af

Or Explorer

http://0.0.0.0:3000/api/MUsers/confirm?uid=150373302744&token=62f6ea48802d5753050dec690048bd474266de72bc7bd841f1ee786dd5f5a36202a6a33850a98968b826dc08e9bde1fd93b86f1df918f7c2f2921bc847c598af
Error:
{
  "error": {
    "name": "TypeError",
    "status": 500,
    "message": "undefined is not a function",
    "stack": "TypeError: undefined is not a function\n    at Function.ArangoDB.evaluateWhere (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-connector-arango/lib/arango.js:100:23)\n    at ArangoDB.all (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-connector-arango/lib/arango.js:539:30)\n    at /home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/dao.js:1474:42\n    at doNotify (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at doNotify (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:93:49)\n    at Function.ObserverMixin._notifyBaseObservers (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:116:5)\n    at Function.ObserverMixin.notifyObserversOf (/home/nyamath/NodeJsPrj/Capto/node_modules/loopback-datasource-juggler/lib/observer.js:91:8)"
  }
}

I suspect that this error is poping up from loopback-connector-arango. 
Is anyone experience this issue before.
Please help me out to overcome from this error. 

Thanks in advance.
Cheers,
Nyamath Ulla khan

**Comment by ullakhan** [comment]
Hi,

I tried putting console log to see the condValue:
Codition value=167130378018

FILE: https://github.com/duffn/loopback-connector-arango/blob/master/lib/arango.js  LINE:100
I found the place and didthe little bit code (Added IF condition to check is really a ARRAY type).  
The condValue variable is not a ARRAY type in my case(167130378018).

if( Array.isArray(condValue) )     // Added this condition

if (condProp === 'id') {
        condProp = '_id';
        if( Array.isArray(condValue) ){                               // Added this condition
          if (condValue.indexOf('/') === -1){
            condValue = model + "/" + condValue;
          }
        }
        else {
          condValue = model + "/" + condValue;
        }
     }
Thereafter I did not get the above mentioned issue. But I am not sure about the above added code does have impact on arango module . Please verify it.

Thanks,
Nyamath Ulla Khan

**Comment by duffn** [comment]
Hello - thanks for your interest in the repository. This version of the LoopBack connector for ArangoDB will no longer be maintained. While not quite ready yet, you should in the future use [loopback-connector-arangodb](https://github.com/nvdnkpr/loopback-connector-arangodb) by @nvdnkpr, the original author.

Thanks.
